version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: institution
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      PGUSER: postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "institution"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    container_name: db

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
    - "ConnectionStrings:DefaultConnection=Host=db;User Id=postgres;Password=123;Database=institution;Port=5432;Pooling=false"
    restart: unless-stopped
    container_name: app

  migration:
    container_name: migrations
    image: mcr.microsoft.com/dotnet/sdk:8.0
    volumes:
      - ./InstitutionStatistic.WebApi/Migrations:/app
      - ./Commands:/app/Commands
    working_dir: /app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["/bin/bash", "Commands/commands.sh"] 


